# Generated by Django 5.1.1 on 2026-10-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='orbit_prompts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
